# <span style="color:RoyalBlue; ">2.3 Pythonプログラミング入門</span>

###### <span style="color: gray ">コード2.1　おためしプログラム</span>

In [1]:
4/2

2.0

###### <span style="color: gray ">コード2.2　四則演算</span>

In [2]:
print(3/2) # 割り算
print(3//2) # 切り捨て除算
print(11%3) # 剰余
print(2**8) # べき乗

1.5
1
2
256


## <span style="color: DeepPink; ">2.3.1キーボードショートカットとMarkdown</span>

###### <span style="color: gray ">コード2.3　Markdown</span>

### Jupyter Notebook ショートカットまとめ
#### Jupyter Notebook ショートカットまとめ
-  <kbd>H</kbd>: ヘルプを表示
-  (新バージョンでは） <kbd>Ctrl</kbd>+ <kbd>Shift</kbd>+<kbd>H</kbd>: ヘルプを表示
-  <kbd>M</kbd>: Markdownセルに変更
- <kbd>Ctrl</kbd>+<kbd>Enter</kbd>: セルの内容を実行
- <kbd>Shift</kbd>+<kbd>Enter</kbd>: セルの内容を実行して下へ
- <kbd>Ctrl</kbd>+<kbd>/</kbd>: コメントアウト
- <kbd>Y</kbd>: Codeセルに変更
-  <kbd>A</kbd>: ひとつ上に空のセルを挿入
-  <kbd>B</kbd>: ひとつ下に空のセルを挿入
- <kbd>D</kbd><kbd>D</kbd>: セルの削除

#### Markdownの書式については下記URLを参照してください
[Markdown書式チート](https://qiita.com/kamorits/items/6f342da395ad57468ae3)

## <span style="color: DeepPink; ">2.3.2 変数の取り扱い</span>

###### <span style="color: gray ">コード2.4　変数の取り扱い</span>

In [3]:
a=10
b=5
S=a**2*3.14
print('円の面積は',S,'です')

円の面積は 314.0 です


## <span style="color: DeepPink; ">2.3.3 リスト</span>

###### <span style="color: gray ">コード2.5　リスト</span>

In [4]:
number=[1,2,3,4,5] # リスト
print(number)

[1, 2, 3, 4, 5]


###### <span style="color: gray ">コード2.6　データ型</span>

In [5]:
# 整数 = int型
# 浮動小数点数 = float型
# 文字列 = str型
# 論理値（True[1], False[0]）= bool型

A="文字です"
print(A)
print("変数のデータ型は",type(A),"です")

文字です
変数のデータ型は <class 'str'> です


###### <span style="color: gray ">コード2.7　リストの操作</span>

In [6]:
data=['身長',175,'体重',60] 
print('リストの中身は', data) # ①
print('リストの長さは',len(data)) # ②
print('リストの最初の要素は',data[0]) # ③リストの最初の要素　pythonでは0から指定する
print('リストの最初の要素は',data[2]) # ④
data[3]=45 # ⑤
print('リストの中身は',data) # ⑥

リストの中身は ['身長', 175, '体重', 60]
リストの長さは 4
リストの最初の要素は 身長
リストの最初の要素は 体重
リストの中身は ['身長', 175, '体重', 45]


## <span style="color: DeepPink; ">2.3.4 タプル</span>

###### <span style="color: gray ">コード2.8　タプル</span>

In [7]:
# タプルの定義
data = ("身長", 175, "体重", 60)
print("タプルの中身は", data)  # タプルの中身を表示
print("タプルの長さは", len(data))  # タプルの長さを表示
print("タプルの最初の要素は", data[0])  # インデックスで要素にアクセス
print("タプルの3番目の要素は", data[2])  # インデックスで要素にアクセス
data[3] = 45  # # タプルはイミュータブルなので値を変更しようとするとエラー

タプルの中身は ('身長', 175, '体重', 60)
タプルの長さは 4
タプルの最初の要素は 身長
タプルの3番目の要素は 体重


TypeError: 'tuple' object does not support item assignment

## <span style="color: DeepPink; ">2.3.5 bool型</span>

###### <span style="color: gray ">コード2.9　bool型と条件式</span>

In [8]:
# bool型（True or False）
bool_integer=100
bool_50=bool_integer>=50
bool_200=bool_integer>=200
print('Bool_integerの値は',bool_integer)
print('bool_integerは50以上ですか？→',bool_50)
print('bool_integerは200以上ですか？→',bool_200)

Bool_integerの値は 100
bool_integerは50以上ですか？→ True
bool_integerは200以上ですか？→ False


###### <span style="color: gray ">コード2.10　bool型の比較演算</span>

In [9]:
a=100
print(a==100) # 等しい
print(a != 100) # 等しくない
print(a>80) # 大なり
print(a<80) # 小なり　　
print(a >= 100) # 以上
print(a <= 100) # 以下

True
False
True
False
True
True


## <span style="color: DeepPink; ">2.3.6 if文</span>

###### <span style="color: gray ">コード2.11　if文</span>

In [10]:
Ymoney=1000
# Ymoney=450
# Ymoney=100
if(Ymoney>=200):
    print('お祭りで何か買えます')
if(Ymoney>=500):
    print('焼きそばが買えます')
elif(200<=Ymoney<500):
        print('りんご飴が買えます')
else:
    print('何も買えません')

お祭りで何か買えます
焼きそばが買えます


###### <span style="color: gray ">コード2.12　インデント</span>

if (条件):<BR>
<font color="Red">インデント→</font>実行文<BR>
elif(条件):<BR>
   <font color="Red">インデント→</font> 実行文<BR>
else:<BR>
    <font color="Red">インデント→</font>実行文<BR>

## <span style="color: DeepPink; ">2.3.7 for文</span>

###### <span style="color: gray ">コード2.13　for文の構造</span>

for 変数 in オブジェクト：<BR>
<font color="Red">インデント→</font>実行文<BR>

###### <span style="color: gray ">コード2.14　for文の具体例</span>

In [11]:
for i in [0,1,2]:
    print(i)

0
1
2


###### <span style="color: gray ">コード2.15　range関数</span>

In [12]:
A = range(5)
print(A)
for i in range(5):
    print(i)

range(0, 5)
0
1
2
3
4


###### <span style="color: gray ">コード2.16　for文と変数</span>

In [13]:
words=["python","による","スペクトル解析"]
for w in words:
    print(w)

python
による
スペクトル解析


## <span style="color: DeepPink; ">2.3.8 関数の定義</span>

###### <span style="color: gray ">コード2.17　defキーワードを使用した関数定義の構造</span>

def 関数名(引数):<BR>
   <font color="Red">インデント→</font> 実行文<BR>
   <font color="Red">インデント→</font> return 戻り値

###### <span style="color: gray ">コード2.18　引数と戻り値をもたない関数</span>

In [14]:
def hello():
    print('hello to chemometorics')
    print('for the spectral analysis')
hello()

hello to chemometorics
for the spectral analysis


###### <span style="color: gray ">コード2.19　引数をもつ関数</span>

In [15]:
def show_hello_to(name1,name2):
    print(name1+'さん、ケモメトリクス解析へようこそ')
    print(name2+'さん、スペクトルが自由に解析できますよ')
show_hello_to('sakai','kato')

sakaiさん、ケモメトリクス解析へようこそ
katoさん、スペクトルが自由に解析できますよ


###### <span style="color: gray ">コード2.20　引数と戻り値をもつ関数</span>

In [16]:
def simple_tashizan(a,b,c):
    p1=a+b
    p2=a+c
    p3=b+c
    return p1,p2,p3

d1,d2,d3=simple_tashizan(10,20,30)
print(d1,d2,d3)

30 40 50


# <span style="color:RoyalBlue; ">2.4 ライブラリ</span>

## <span style="color: DeepPink; ">2.4.2 ライブラリのインストールとインポート</span>

###### <span style="color: gray ">コード2.21　ライブラリのインポート方法①</span>

In [17]:
import numpy

###### <span style="color: gray ">コード2.22　ライブラリのインポート方法②</span>

In [18]:
from numpy import array

###### <span style="color: gray ">コード2.23　ライブラリのインポート方法③</span>

In [19]:
import numpy as np
a = np.array([1, 2, 3])

###### <span style="color: gray ">コード2.24　asキーワードの慣例</span>

In [20]:
import pandas as pd
import matplotlib.pyplot as plt

## <span style="color: DeepPink; ">2.4.4 ライブラリの利用方法</span>

###### <span style="color: gray ">コード2.24　メソッド</span>

In [21]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6]) # ① 1次元配列を作成
print(array)
reshaped_array = array.reshape((2, 3)) # ② reshapeメソッドを使用して配列の形状を変更
print(reshaped_array)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


###### <span style="color: gray ">コード2.25　アトリビュート</span>

In [22]:
import numpy as np
array = np.array([1, 2, 3])
print(array.shape) # (3,) - 3要素の1次元配列
print(array.dtype) # float64 - 各要素のデータ型は64ビット浮動小数点数

(3,)
int32
